apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      name: petclinic
  template:
    metadata:
      labels:
        name: petclinic
    spec:
      containers:
        - name: petclinic
          image: 992382714938.dkr.ecr.us-east-1.amazonaws.com/spring-petclinic:${BUILD_NUMBER}
          ports:
            - containerPort: 8080
          



---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
spec:
  type: LoadBalancer
  selector:
    name: petclinic
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
